superman:
    path: /superman
    controller: App\Controller\SupermanController::superman

login:
    path: /login
    controller: App\Controller\LoginController::login

registerPage:
    path: /register
    controller: App\Controller\LoginController::register

forgotPassword:
    path: /forgot-password
    controller: App\Controller\LoginController::forgotPassword



