superman:
    path: /superman
    controller: App\Controller\SupermanController::superman

login:
    path: /login
    controller: App\Controller\AuthenticationController::login

registerPage:
    path: /register
    controller: App\Controller\AuthenticationController::register

forgotPassword:
    path: /forgot-password
    controller: App\Controller\AuthenticationController::forgotPassword

resetPassword:
    path: /reset-password
    controller: App\Controller\AuthenticationController::resetPassword

projects:
    resource: projects_routes.yaml
    prefix: /projects

explore:
    path: /explore
    controller: App\Controller\ExploreProjectsController::explore

