homepage:
    path: /
    controller: App\Controller\HomepageController::homepage


# config/routes.yaml
# the "app_lucky_number" route name is not important yet
app_login:
    path: /login
    controller: App\Controller\LoginController::login

app_superman:
    path: /superman
    controller: App\Controller\SupermanController::superman

