homepage:
    path: /{_locale}
    controller: App\Controller\HomepageController::homepage
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

app:
    resource: routes/app_routes.yaml
    prefix: /{_locale}
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

logout:
    path: /logout
